### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by yonkwon** [yonkwon/SEBC#1]

**Comment by yonkwon** [comment]
vm.swappiness changed after reboot. Fixed with "sudo sysctl -p"

**Comment by yonkwon** [comment]
Forgot to add ' ' while mysql> GRANT REPLICATION SLAVE ON *.* TO 'user'@'FQDN' IDENTIFIED BY 'password'

**Comment by yonkwon** [comment]
innoDB config in my.conf is making mysql process unable to start. Trying to lower numbers

**Comment by yonkwon** [comment]
Current working config of my.conf

[client]
port            = 3306
socket          = /var/run/mysqld/mysqld.sock

# Here is entries for some specific programs
# The following values assume you have at least 32M ram

# This was formally known as [safe_mysqld]. Both versions are currently parsed.
[mysqld_safe]
socket          = /var/run/mysqld/mysqld.sock
nice            = 0

[mysqld]
# Cloudera Options
transaction-isolation = READ-COMMITTED
read_buffer_size = 2M
read_rnd_buffer_size = 16M
sort_buffer_size = 8M
join_buffer_size = 8M

# InnoDB settings
innodb_file_per_table = 1
innodb_flush_log_at_trx_commit  = 2
innodb_log_buffer_size = 64M
innodb_buffer_pool_size = 1G
innodb_thread_concurrency = 8
innodb_flush_method = O_DIRECT
innodb_log_file_size = 512M

#
# * Basic Settings
#
user            = mysql
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
port            = 3306
basedir         = /usr
datadir         = /var/lib/mysql
tmpdir          = /tmp
lc-messages-dir = /usr/share/mysql
skip-external-locking
#
# Instead of skip-networking the default is now to listen only on
# localhost which is more compatible and is not less secure.
bind-address            = 127.0.0.1
#
# * Fine Tuning
#
key_buffer              = 32M
max_allowed_packet      = 32M
thread_stack            = 256K
thread_cache_size       = 64
# This replaces the startup script and checks MyISAM tables if needed
# the first time they are touched
myisam-recover         = BACKUP
#max_connections        = 100
#table_cache            = 64
#thread_concurrency     = 10
#
# * Query Cache Configuration
#
query_cache_limit       = 8M
query_cache_size        = 64M
query_cache_type        = 1

#
# * Logging and Replication
#
# Both location gets rotated by the cronjob.
# Be aware that this log type is a performance killer.
# As of 5.1 you can enable the log at runtime!
#general_log_file        = /var/log/mysql/mysql.log
#general_log             = 1
#
# Error log - should be very few entries.
#
log_error = /var/log/mysql/error.log
#
# Here you can see queries with especially long duration
#log_slow_queries       = /var/log/mysql/mysql-slow.log
#long_query_time = 2
#log-queries-not-using-indexes
#
# The following can be used as easy to replay backup logs or for replication.
# note: if you are setting up a replication slave, see README.Debian about
#       other settings you may need to change.
#server-id              = 1
#log_bin                        = /var/log/mysql/mysql-bin.log
expire_logs_days        = 10
max_binlog_size         = 100M
#binlog_do_db           = include_database_name
#binlog_ignore_db       = include_database_name
#
# * InnoDB
#
# InnoDB is enabled by default with a 10MB datafile in /var/lib/mysql/.
# Read the manual for more InnoDB related options. There are many!
#
# * Security Features
#
# Read the manual, too, if you want chroot!
# chroot = /var/lib/mysql/
#
# For generating SSL certificates I recommend the OpenSSL GUI "tinyca".
#
# ssl-ca=/etc/mysql/cacert.pem
# ssl-cert=/etc/mysql/server-cert.pem
# ssl-key=/etc/mysql/server-key.pem


[mysqldump]
quick
quote-names
max_allowed_packet      = 16M

[mysql]
#no-auto-rehash # faster start of mysql but no tab completition

[isamchk]
key_buffer              = 16M

#
# * IMPORTANT: Additional settings that can override those from this file!
#   The files must end with '.cnf', otherwise they'll be ignored.
#
!includedir /etc/mysql/conf.d/

**Comment by yonkwon** [comment]
Encountered 'empty log' error when issued SHOW MASTER STATUS; in mysql. Fixed by enabling log as below in my.conf

[mysqld]
log-error=/var/log/mysql/mysql.err
log-bin = /var/log/mysql/mysql-replication.log
Then run the following:

service mysql stop
mkdir /var/log/mysql
chown -R mysql:mysql /var/log/mysql
service mysql start

**Comment by mfernest** [comment]
Which lab step are you currently working?

**Comment by yonkwon** [comment]
'START SLAVE' returned an error "ERROR 1200 (HY000): The server is not configured as slave; fix in config file or with CHANGE MASTER TO". Changed AWS security group setting to allow all traffic between instances. Then restarted mysql process on REPLICA server. SLAVE started successfully

**Comment by yonkwon** [comment]
Hi Michael,

Just installed CDH manager but haven’t configured yet. Thank you.

Cheers
Daniel Kwon

**Comment by yonkwon** [comment]
Can't access CDH from my laptop. I can ping the host from my terminal though

**Comment by yonkwon** [comment]
Exhausted available authentication methods (Error- during specifying CDH cluster hosts)
https://community.cloudera.com/t5/Cloudera-Manager-Installation/Exhausted-available-authentication-methods/m-p/28462#M4731 

Since I'm using Ubuntu. I needed to add my user 'ubuntu' to sudo user group
sudo usermod -aG sudo ubuntu

**Comment by yonkwon** [comment]
Encountered DB connection error when setting up Hive, Hue, OOzie and etc. Changed hostname from FQDN to 'localhost'.

**Comment by yonkwon** [comment]
Can't start NameNode. In the role log,

java.io.IOException: NameNode is not formatted.

**Comment by yonkwon** [comment]
Encountered exception loading fsimage
java.io.FileNotFoundException: /dfs/nn/current/VERSION (Permission denied)

**Comment by yonkwon** [comment]
Failed to start Hive, OOzie, Yarn, Zookeeper...

**Comment by yonkwon** [comment]
Ok OOzie was easy. 

Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'oozie.VALIDATE_CONN' doesn't exist 

Fixed by : creating Table for OOzie. 

https://community.cloudera.com/t5/Cloudera-Manager-Installation/Oozie-Installation-with-Mysql/m-p/13022#M1466

**Comment by yonkwon** [comment]
YARN:
 Error starting JobHistoryServer
org.apache.hadoop.yarn.exceptions.YarnRuntimeException: Error creating done directory: 

Fixed by
sudo -u hdfs hadoop fs -chmod -R 777 /

**Comment by yonkwon** [comment]
Zookeeper error requested creating a directory. After creating the directory, the issue solved
